export const ASSETS = {
  logoHome: 'textures/logo_astranova_mahjong.png',
  visibilityView: 'textures/icon_visibility_view.png',
  visibilityHide: 'textures/icon_visibility_hide.png',
  modeOffline: 'textures/icon_mode_offline.png',
  modeOnline: 'textures/icon_mode_online.png',
  modeGacha: 'textures/icon_mode_gacha.png',
  featureChara: 'textures/icon_feature_chara.png',
  featureEquipment: 'textures/icon_feature_equipment.png',
  utilityLanguage: 'textures/icon_utility_language.png',
  utilitySfxOn: 'textures/icon_utility_sfx_on.png',
  utilitySfxOff: 'textures/icon_utility_sfx_off.png',
  utilityBgmOn: 'textures/icon_utility_bgm_on.png',
  utilityBgmOff: 'textures/icon_utility_bgm_off.png',
  utilityTransfer: 'textures/icon_utility_transfer.png',
  matchEmote: 'textures/icon_match_emote.png',
  matchAuto: 'textures/icon_match_auto.png',
  matchHelp: 'textures/icon_match_help.png',
  uiSparkle: 'textures/deco_sparkle.png',
  gachaMachine: 'textures/sym_gacha_machine.png',
  rewardCardBack: 'textures/panel_reward_card_back.png',
  lobbyBackground: 'textures/bg_lobby_daily.png',
  characterAya: 'textures/sym_character_asteria_outfit_1.png',
  characterMio: 'textures/sym_character_lumi_outfit_1.png',
  characterSora: 'textures/sym_character_nyx_outfit_1.png',
  tableCelestial: 'textures/bg_table_daily.png',
  tileShell: 'textures/panel_tile_shell.png',
  tileBackCelestial: 'textures/panel_tile_back_daily.png',
  matchAction: {
    en: {
      chi: 'textures/txt_action_chi_en.png', pong: 'textures/txt_action_pong_en.png', kong: 'textures/txt_action_kong_en.png',
      ready: 'textures/txt_action_ready_en.png', win: 'textures/txt_action_win_en.png', selfDraw: 'textures/txt_action_self_draw_en.png',
    },
    'zh-TW': {
      chi: 'textures/txt_action_chi.png', pong: 'textures/txt_action_pong.png', kong: 'textures/txt_action_kong.png',
      ready: 'textures/txt_action_ready.png', win: 'textures/txt_action_win.png', selfDraw: 'textures/txt_action_self_draw.png',
    },
    'zh-CN': {
      chi: 'textures/txt_action_chi.png', pong: 'textures/txt_action_pong.png', kong: 'textures/txt_action_kong_zh_cn.png',
      ready: 'textures/txt_action_ready_zh_cn.png', win: 'textures/txt_action_win.png', selfDraw: 'textures/txt_action_self_draw.png',
    },
    ja: {
      chi: 'textures/txt_action_chi_ja.png', pong: 'textures/txt_action_pong_ja.png', kong: 'textures/txt_action_kong_ja.png',
      ready: 'textures/txt_action_ready_ja.png', win: 'textures/txt_action_win_ja.png', selfDraw: 'textures/txt_action_self_draw_ja.png',
    },
  },
  bgmBase: 'audio/bgm_base.mp3',
  bgmRoom: 'audio/bgm_room.mp3',
  bgmMatch: 'audio/bgm_match.mp3',
  bgmReady: 'audio/bgm_ready.mp3',
  sfxUiClick: 'audio/sfx_ui_click.mp3',
  sfxUiInvalid: 'audio/sfx_ui_invalid.mp3',
  sfxUiSpecial: 'audio/sfx_ui_special.mp3',
  sfxReady: 'audio/sfx_ready.mp3',
  sfxWin: 'audio/sfx_win.mp3',
  sfxTileDiscard: 'audio/sfx_tile_discard.mp3',
  sfxTileHover: 'audio/sfx_tile_hover.mp3',
  sfxTileArrange: 'audio/sfx_tile_arrange.mp3',
} as const;

export function tileFaceAsset(tile: string): string {
  return `textures/sym_tile_${tile}.png`;
}
