export const ASSETS = {
  logoHome: 'textures/logo_astranova_mahjong.webp',
  visibilityView: 'textures/icon_visibility_view.webp',
  visibilityHide: 'textures/icon_visibility_hide.webp',
  modeOffline: 'textures/icon_mode_offline.webp',
  modeOnline: 'textures/icon_mode_online.webp',
  modeGacha: 'textures/icon_mode_gacha.webp',
  featureChara: 'textures/icon_feature_chara.webp',
  featureEquipment: 'textures/icon_feature_equipment.webp',
  utilityLanguage: 'textures/icon_utility_language.webp',
  utilitySfxOn: 'textures/icon_utility_sfx_on.webp',
  utilitySfxOff: 'textures/icon_utility_sfx_off.webp',
  utilityBgmOn: 'textures/icon_utility_bgm_on.webp',
  utilityBgmOff: 'textures/icon_utility_bgm_off.webp',
  utilityTransfer: 'textures/icon_utility_transfer.webp',
  matchEmote: 'textures/icon_match_emote.webp',
  matchAuto: 'textures/icon_match_auto.webp',
  matchHelp: 'textures/icon_match_help.webp',
  uiSparkle: 'textures/deco_sparkle.webp',
  gachaMachine: 'textures/sym_gacha_machine.webp',
  rewardCardBack: 'textures/panel_reward_card_back.webp',
  lobbyBackground: 'textures/bg_lobby_daily.webp',
  characterAya: 'textures/sym_character_asteria_outfit_1.webp',
  characterMio: 'textures/sym_character_lumi_outfit_1.webp',
  characterSora: 'textures/sym_character_nyx_outfit_1.webp',
  tableCelestial: 'textures/bg_table_daily.webp',
  tileShell: 'textures/panel_tile_shell.webp',
  tileBackCelestial: 'textures/panel_tile_back_daily.webp',
  matchAction: {
    en: {
      chi: 'textures/txt_action_chi_en.webp', pong: 'textures/txt_action_pong_en.webp', kong: 'textures/txt_action_kong_en.webp',
      ready: 'textures/txt_action_ready_en.webp', win: 'textures/txt_action_win_en.webp', selfDraw: 'textures/txt_action_self_draw_en.webp',
    },
    'zh-TW': {
      chi: 'textures/txt_action_chi.webp', pong: 'textures/txt_action_pong.webp', kong: 'textures/txt_action_kong.webp',
      ready: 'textures/txt_action_ready.webp', win: 'textures/txt_action_win.webp', selfDraw: 'textures/txt_action_self_draw.webp',
    },
    'zh-CN': {
      chi: 'textures/txt_action_chi.webp', pong: 'textures/txt_action_pong.webp', kong: 'textures/txt_action_kong_zh_cn.webp',
      ready: 'textures/txt_action_ready_zh_cn.webp', win: 'textures/txt_action_win.webp', selfDraw: 'textures/txt_action_self_draw.webp',
    },
    ja: {
      chi: 'textures/txt_action_chi_ja.webp', pong: 'textures/txt_action_pong_ja.webp', kong: 'textures/txt_action_kong_ja.webp',
      ready: 'textures/txt_action_ready_ja.webp', win: 'textures/txt_action_win_ja.webp', selfDraw: 'textures/txt_action_self_draw_ja.webp',
    },
  },
  bgmBase: 'audio/bgm_base.mp3',
  bgmRoom: 'audio/bgm_room.mp3',
  bgmMatch: 'audio/bgm_match.mp3',
  bgmReady: 'audio/bgm_ready.mp3',
  sfxUiClick: 'audio/sfx_ui_click.mp3',
  sfxUiInvalid: 'audio/sfx_ui_invalid.mp3',
  sfxUiSpecial: 'audio/sfx_ui_special.mp3',
  sfxReady: 'audio/sfx_ready.mp3',
  sfxWin: 'audio/sfx_win.mp3',
  sfxTileDiscard: 'audio/sfx_tile_discard.mp3',
  sfxTileHover: 'audio/sfx_tile_hover.mp3',
  sfxTileArrange: 'audio/sfx_tile_arrange.mp3',
} as const;

export function tileFaceAsset(tile: string): string {
  return `textures/sym_tile_${tile}.webp`;
}
